### ISSUE TITLE
Published NPM Version Missing Files

### ISSUE THREAD

**Issue by interrobrian** [kandhavivekraj/git-changed-files#4]
The published version of this package is missing the `src` directory, which causes the following exception when you attempt to call `require("git-changed-files")`:

```
Error: Cannot find module './src/fetchGitStatus'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by kandhavivekraj** [comment]
@interrobrian Please try with `v0.1.1`. Thanks for reporting the issue.
